# ── SERVICE.YAML ──
# Tells Kubernetes HOW to expose your app to the outside world

apiVersion: v1
# apiVersion: v1 = core Kubernetes API (used for Services)

kind: Service
# kind: Service = exposes your pods to network traffic

metadata:
  name: k8s-mac-project-service
  # name: unique name of this Service in Kubernetes
  labels:
    app: k8s-mac-project

spec:
  type: NodePort
  # type: NodePort = exposes the service on a port on the node
  # This lets us access the website from our Mac browser
  # Other types: ClusterIP (internal only), LoadBalancer (cloud)

  selector:
    app: k8s-mac-project
    # selector: finds pods with this label to send traffic to
    # must match the labels in deployment.yaml

  ports:
    - name: http
      protocol: TCP
      port: 80
      # port: the port the Service listens on internally
      targetPort: 80
      # targetPort: the port on the container to forward to
      # matches containerPort in deployment.yaml
      nodePort: 30080
      # nodePort: the port YOU use in your browser
      # visit localhost:30080 to see your website!
